---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by Cool.
--- DateTime: 2024/7/14 下午7:44
---

-- 比较线程标识与锁中的标识是否一致
local lock_id = redis.call('get', KEYS[1])
if (redis.call('get',KEYS[1])==ARGV[1]) then
    -- 释放锁 del key
    redis.call('del',KEYS[1])
end
return 0